### ISSUE TITLE
Misschien beter voor website snelheid om kleinere images op te halen en die te renderen

### ISSUE THREAD

**Issue by Michelwas97** [WyroneBlue/rijksmuseum-gallery-app#5]
https://github.com/WyroneBlue/rijksmuseum-gallery-app/blob/f5192c8c4ab5f39213de31ade8929dfa506aea74/js/home.js#L67

**Comment by WyroneBlue** [comment]
Ik haal de kleinere image op door nog een fetch te doen naar een endpoint die een lijst van verschillende soorten kwaliteiten ophaalt van de desbetreffende art
